%global srcname livesplit-one-druid

Name: livesplit-one
Version: 0.7.2
Release: 1%{?date}.git%{?commit_short}%{?dist}
Summary: A desktop version of LiveSplit One (hoxi's fork).

License: MIT
URL: https://github.com/hoXyy/livesplit-one-druid
# Source tarball is auto-generated by COPR's git builder.
Source0: %{srcname}-%{commit}.tar.gz

BuildRequires:  cargo
BuildRequires:  rust
BuildRequires:  git
BuildRequires:  libgtk-3-devel
BuildRequires:  pkgconfig
BuildRequires:  desktop-file-utils

Requires:       libgtk-3

%description
A desktop version of LiveSplit One (hoxi's fork).

%prep
%setup -qn %{srcname}-%{commit}

%build
cargo build --release %{?_smp_mflags}

%install
install -Dpm 0755 target/release/%{name} %{buildroot}%{_bindir}/%{name}
install -Dpm 0644 packaging/%{name}.desktop %{buildroot}%{_datadir}/applications/%{name}.desktop
install -Dpm 0644 icons/icon.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg
install -Dpm 0644 icons/icon.png %{buildroot}%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
desktop-file-validate %{buildroot}%{_datadir}/applications/%{name}.desktop

%files
%{_bindir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg
%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
%doc README.md

%changelog
* Sat Jun 13 2026 Automatic COPR Build <noreply@copr.fedorainfracloud.org> 0.7.2-1
- Initial package
