name: Rust

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'dev'
    tags:
      - '*'

# The colors mess with the problem matcher.
# env:
  # CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        label:
          - Linux x86_64
          - Linux x86_64-v3

        include:
          - label: Linux x86_64
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            features: auto-splitting

          - label: Linux x86_64-v3
            target: x86_64-unknown-linux-gnu
            target_rename: x86_64_v3-unknown-linux-gnu
            rust_flags: -C target-cpu=x86-64-v3
            os: ubuntu-latest
            features: auto-splitting

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: 'stable'

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes libgtk-4-dev libadwaita-1-dev

      - name: Build
        run: bash .github/workflows/build.sh
        env:
          TARGET: ${{ matrix.target }}
          IS_DEPLOY: ${{ startsWith(github.ref, 'refs/tags/') }}
          FEATURES: ${{ matrix.features }}
          RUSTFLAGS: ${{ matrix.rust_flags }}

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        run: bash .github/workflows/before_deploy.sh
        env:
          TARGET: ${{ matrix.target }}
          RELEASE_TARGET: ${{ matrix.target_rename || matrix.target }}

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref, 'pre') }}
          generate_release_notes: true
          files: livesplit-one-*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          components: clippy

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes libgtk-4-dev libadwaita-1-dev

      - name: Run Clippy
        run: cargo clippy --all-features

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt -- --check || true
